"""stripe customer table

Revision ID: 151d1b0fb598
Revises: 8c1b0067412f
Create Date: 2023-10-19 09:36:20.593783

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '151d1b0fb598'
down_revision = '8c1b0067412f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('stripe_customer',
    sa.Column('customer_id', sa.String(), nullable=False),
    sa.Column('slack_organization_id', sa.String(), nullable=False, unique=True),
    sa.Column('created_at', sa.DateTime(), nullable=False, default=sa.func.now()),
    sa.Column('is_premium', sa.Boolean(), nullable=False),
    sa.Column('premium_from', sa.DateTime(), nullable=True),
    sa.Column('premium_to', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['slack_organization_id'], ['slack_organizations.team_id'], ),
    sa.PrimaryKeyConstraint('customer_id'),
    )
    op.create_index(op.f('ix_stripe_customer_slack_organization_id'), 'stripe_customer', ['slack_organization_id'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_stripe_customer_slack_organization_id'), table_name='stripe_customer')
    op.drop_table('stripe_customer')
    # ### end Alembic commands ###
