"""Adds Stripe customer table

Revision ID: 6043629f6418
Revises: 8c1b0067412f
Create Date: 2023-10-16 20:22:45.115608

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6043629f6418'
down_revision = '8c1b0067412f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('stripe_customer',
    sa.Column('customer_id', sa.String(), nullable=False),
    sa.Column('team_id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('is_premium', sa.Boolean(), nullable=False),
    sa.Column('premium_from', sa.DateTime(), nullable=True),
    sa.Column('premium_to', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['team_id'], ['slack_organizations.team_id'], ),
    sa.PrimaryKeyConstraint('customer_id')
    )
    op.create_index(op.f('ix_stripe_customer_team_id'), 'stripe_customer', ['team_id'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_stripe_customer_team_id'), table_name='stripe_customer')
    op.drop_table('stripe_customer')
    # ### end Alembic commands ###
