#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

if ! git diff --cached --exit-code -s application/next-frontend
then
	echo "Files changed in next-frontend"
	cd application/next-frontend
	npx lint-staged 
	npm run typecheck
	cd ../..
fi
