FROM python:3.14-slim

WORKDIR /srv/backend

COPY backend/requirements.txt backend/requirements-test.txt /tmp/
WORKDIR /tmp

RUN apt-get update && \
    apt-get install -y --no-install-recommends \
        gcc \
        libc6-dev \
        libpq5 \
        libpq-dev \
        postgresql-client \
        postgresql-contrib && \
    pip install --no-cache-dir -r requirements.txt && \
    pip install --no-cache-dir -r requirements-test.txt && \
    apt-get purge -y --auto-remove gcc libc6-dev libpq-dev && \
    rm -rf /var/lib/apt/lists/*

WORKDIR /srv/backend

CMD flask run
