FROM python:3.14-slim

WORKDIR /srv/backend

COPY backend/requirements.txt /tmp
WORKDIR /tmp

RUN apt-get update && \
    apt-get install -y --no-install-recommends \
        gcc \
        libc6-dev \
        libpq5 \
        libpq-dev && \
    pip install --no-cache-dir -r requirements.txt && \
    apt-get purge -y --auto-remove gcc libc6-dev libpq-dev && \
    rm -rf /var/lib/apt/lists/*

WORKDIR /srv/backend

CMD flask run
