
#body of checkout.session.completed event

d = {
    'id': 'cs_test_a10mNUDZXqTw7dir5aWqXzIEP0MPcWIZVAgSrVooSURJrAlcnj6pd78dWz',
    'object': 'checkout.session',
    'after_expiration': None,
    'allow_promotion_codes': None,
    'amount_subtotal': 5000,
    'amount_total': 5000,
    'automatic_tax': {'enabled': False, 'status': None},
    'billing_address_collection': None,
    'cancel_url': 'https://yahoo.com',
    'client_reference_id': '10',
    'client_secret': None,
    'consent': None,
    'consent_collection': None,
    'created': 1697639579,
    'currency': 'nok',
    'currency_conversion': None,
    'custom_fields': [],
    'custom_text': {'shipping_address': None, 'submit': None,
                    'terms_of_service_acceptance': None},
    'customer': 'cus_OqHNNuS3FMQC54',
    'customer_creation': 'always',
    'customer_details': {
        'address': {
            'city': None,
            'country': 'NO',
            'line1': None,
            'line2': None,
            'postal_code': None,
            'state': None,
            },
        'email': 't@t.no',
        'name': 'jacob',
        'phone': None,
        'tax_exempt': 'none',
        'tax_ids': [],
        },
    'customer_email': None,
    'expires_at': 1697725979,
    'invoice': 'in_1O2aoeKP3o6MCdzWNkXhO0tv',
    'invoice_creation': None,
    'livemode': False,
    'locale': None,
    'metadata': {},
    'mode': 'subscription',
    'payment_intent': None,
    'payment_link': None,
    'payment_method_collection': 'always',
    'payment_method_configuration_details': {'id': 'pmc_1O0mTTKP3o6MCdzWSPuBhgio',
            'parent': None},
    'payment_method_options': None,
    'payment_method_types': ['card'],
    'payment_status': 'paid',
    'phone_number_collection': {'enabled': False},
    'recovered_from': None,
    'setup_intent': None,
    'shipping_address_collection': None,
    'shipping_cost': None,
    'shipping_details': None,
    'shipping_options': [],
    'status': 'complete',
    'submit_type': None,
    'subscription': 'sub_1O2aodKP3o6MCdzWMFxed5rw',
    'success_url': 'https://google.com',
    'total_details': {'amount_discount': 0, 'amount_shipping': 0,
                      'amount_tax': 0},
    'ui_mode': 'hosted',
    'url': None,
    }