name: Frontend
on:
  pull_request:
    types: [opened, synchronize, reopened, closed]
    branches:
      - main
    paths:
      - "application/frontend/**"
  push:
    branches:
      - main
    paths:
      - "application/frontend/**"
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
      - name: Set up Node 20.x
        uses: actions/setup-node@v3
        with:
          node-version: 20.x
          cache: "npm"
          cache-dependency-path: application/frontend/package-lock.json
      - name: Install dependencies
        working-directory: application/frontend
        run: npm ci
      - name: Build
        working-directory: application/frontend
        run: npm run build
