name: Bump version
on:
  pull_request:
    types:
      - closed
    branches:
      - main
    paths:
      - application/**
      - infrastructure/**
      - .github/workflows/versioning.yml
jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.sha }}
          fetch-depth: "0"
      - name: Set up Node.js
        uses: actions/setup-node@v3
      - name: Install dependencies
        run: npm install
        working-directory: application/frontend
      - name: Build bundle
        run: npm run build:production
        working-directory: application/frontend
        env:
          BACKEND_URI: https://api.www.pizzabot.app
          NEXT_PUBLIC_BACKEND_URI: https://api.www.pizzabot.app # This is required for next-frontend when production ready
      - name: Remove build gitignore
        run: rm public/.gitignore
        working-directory: application/frontend
      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Automated Build
          branch: build
          push_options: "--force"
          create_branch: true

  create-tag:
    needs: build
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
        with:
          ref: build
          fetch-depth: "0"

      - name: Bump version and push tag
        uses: anothrNick/github-tag-action@1.55.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          WITH_V: true
          DEFAULT_BRANCH: build
