name: Bump version
on:
  pull_request:
    types:
      - closed
    branches:
      - main
    paths:
      - application/**
      - infrastructure/**
      - .github/workflows/versioning.yml
jobs:
  commit-version:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.sha }}
          fetch-depth: "0"
      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Automated Versioning
          branch: build
          push_options: "--force"
          create_branch: true

  create-tag:
    needs: commit-version
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
        with:
          ref: build
          fetch-depth: "0"

      - name: Bump version and push tag
        uses: anothrNick/github-tag-action@1.55.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          WITH_V: true
          DEFAULT_BRANCH: build
